<?xml version="1.0" ?>
<package format="3">
  <name>fairino_hw</name>
  <version>0.0.1</version>
  <description>
    MoveIt Pro hardware configuration for the Fairino FR5 robot
  </description>

  <maintainer email="sbadamikar@picknik.ai">Sanchit Badamikar</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>fairino_mock</exec_depend>
  <exec_depend>fairino_description</exec_depend>
  <exec_depend>fairino_hardware</exec_depend>
  <exec_depend>fairino_msgs</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
